# Generated by Django 3.2.7 on 2021-09-04 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210904_1258'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='balancelog',
            options={'default_related_name': 'logs', 'verbose_name': 'Лог баланса', 'verbose_name_plural': 'Логи баланса'},
        ),
        migrations.AlterField(
            model_name='balancelog',
            name='balance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='main.balance', verbose_name='Баланс'),
        ),
    ]
