# Generated by Django 3.2.7 on 2021-09-04 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210904_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='image',
            field=models.FileField(default='', upload_to='', verbose_name='Картинка'),
            preserve_default=False,
        ),
    ]
