# Generated by Django 3.2.7 on 2021-09-04 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_achievement_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='achievement',
            options={'verbose_name': 'Достижение', 'verbose_name_plural': 'Достижения'},
        ),
        migrations.AlterModelOptions(
            name='balancelog',
            options={'default_related_name': 'logs', 'verbose_name': 'Лог баланса', 'verbose_name_plural': 'Логи балансов'},
        ),
        migrations.AlterModelOptions(
            name='commandbalance',
            options={'default_related_name': 'command_balances', 'verbose_name': 'Актуальный баланс команды', 'verbose_name_plural': 'Актуальные балансы команды'},
        ),
        migrations.AlterModelOptions(
            name='quest',
            options={'verbose_name': 'Задание', 'verbose_name_plural': 'Задания'},
        ),
        migrations.AlterField(
            model_name='achievement',
            name='additional_data',
            field=models.JSONField(blank=True, default=dict, verbose_name='Доп данные'),
        ),
        migrations.AlterField(
            model_name='balance',
            name='additional_data',
            field=models.JSONField(blank=True, default=dict, verbose_name='Доп данные'),
        ),
        migrations.AlterField(
            model_name='balancelog',
            name='additional_data',
            field=models.JSONField(blank=True, default=dict, verbose_name='Доп данные'),
        ),
        migrations.AlterField(
            model_name='commandbalance',
            name='additional_data',
            field=models.JSONField(blank=True, default=dict, verbose_name='Доп данные'),
        ),
        migrations.AlterField(
            model_name='quest',
            name='additional_data',
            field=models.JSONField(blank=True, default=dict, verbose_name='Доп данные'),
        ),
        migrations.AlterField(
            model_name='raweventlog',
            name='additional_data',
            field=models.JSONField(blank=True, default=dict, verbose_name='Доп данные'),
        ),
        migrations.AlterField(
            model_name='scorelog',
            name='additional_data',
            field=models.JSONField(blank=True, default=dict, verbose_name='Доп данные'),
        ),
        migrations.AlterField(
            model_name='userbalance',
            name='additional_data',
            field=models.JSONField(blank=True, default=dict, verbose_name='Доп данные'),
        ),
    ]
