version: "3"

x-defaults: &defaults
  image: hack2021
  build:
    dockerfile: docker/Dockerfile${SUFFIX}
    context: .
  environment:
    DEBUG: 1
    DATABASE_URL: psql://postgres:password@db:5432/hack2021
    CACHE_URL: redis://redis:6379/0
    BROKER_URL: redis://redis:6379/0
    WAIT_TARGETS: db:5432 redis:6379
    ENV_NAME: prod
    RUN_TASKS_LOCAL: 0
    BEAUTY_ADMIN: 1
  depends_on:
    - db
    - redis
  restart: unless-stopped

services:
  backend:
    ports:
      - "80:8000"
    <<: *defaults
    volumes:
      - ./_storage/:/app/_storage/

  worker:
    <<: *defaults
    command: ["worker"]

  scheduler:
    <<: *defaults
    command: ["scheduler"]

  redis:
    image: redis:alpine
    restart: unless-stopped

  db:
    image: postgres:12-alpine
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_DB: hack2021
      POSTGRES_PASSWORD: password
    volumes:
      - db:/var/lib/postgresql/data/pgdata
    restart: unless-stopped


volumes:
  db: {}
