# Generated by Django 3.2.7 on 2021-09-04 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='external_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Внешний идентификатор'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='settings',
            field=models.JSONField(default=dict, verbose_name='Персональные настройки'),
        ),
    ]
